apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend-app.fullname" . }} # flow file _helpers.pkl
  labels: 
    {{ include "backend-app.labels" . | nindent 4 }} # flow file _helpers.pkl

spec:
  replicas: {{ .Values.replicaCount }}
  selector: 
    matchLabels: 
      {{ include "backend-app.selectorLabels" . | nindent 6 }}
  
  template:
    metadata:
      labels: {{ include "backend-app.selectorLabels" . | nindent 8}}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports: 
            - name: http 
              containerPort: 8000
          envFrom: 
            - configMapRef:
                name: {{ include "backend-app.fullname" . }}
            - secretRef: 
                name: {{ .Values.secretName }}
          resources: {{ toYaml .Values.resources | nindent 12}}
